logging:
    file:
        name: /var/log/api-desafiobdc.log
    level:
        com:
            bdc:
                desafio: DEBUG
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:desafiobdcdb;
        username: sa
    flyway:
        baseline-on-migrate: true
        enabled: true
        locations: classpath:db/migration
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
