CREATE TABLE UNIDADEFEDERATIVA  (
	IDUF BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	NOME VARCHAR(100) NOT NULL,
	SIGLA VARCHAR(2) NOT NULL
);

CREATE TABLE CIDADE  (
	IDCIDADE BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
    IDUF BIGINT, 
	FOREIGN KEY (IDUF) REFERENCES UNIDADEFEDERATIVA(IDUF)
);

CREATE TABLE ENDERECO  (
	IDENDERECO BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	BAIRRO VARCHAR(100) NOT NULL,
	LOGRADOURO VARCHAR(200) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	IDCIDADE BIGINT,
	FOREIGN KEY (IDCIDADE) REFERENCES CIDADE(IDCIDADE)
);

CREATE TABLE PERFIL  (
	IDPERFIL BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO  (
	IDUSUARIO BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	NOME VARCHAR(100) NOT NULL,
	SENHA VARCHAR(10) NOT NULL,
	IDENDERECO BIGINT,
	IDPERFIL BIGINT,
	FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO(IDENDERECO),
	FOREIGN KEY (IDPERFIL) REFERENCES PERFIL(IDPERFIL)
);
